export const STORE_FETCHED_CATEGORIES = 'STORE_FETCHED_CATEGORIES'
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED'

export const STORE_FETCHED_PAGES = 'STORE_FETCHED_PAGES'
export const PAGES_LOADED = 'PAGES_LOADED'

export const STORE_FETCHED_POSTS = 'STORE_FETCHED_POSTS'
export const POSTS_LOADED = 'POSTS_LOADED'
export const POST_LOADED = 'POST_LOADED'
export const POST_DETAIL_LOADING = 'POST_DETAIL_LOADING'

export const STORE_FETCHED_MORE_POSTS = 'STORE_FETCHED_MORE_POSTS'
export const POSTS_LOADING = 'POSTS_LOADING'
export const POSTS_REACHED_MAX = 'POSTS_REACHED_MAX'

export const STORE_FETCHED_SLIDES = 'STORE_FETCHED_SLIDES'
export const SLIDES_LOADED = 'SLIDES_LOADED'

export const STORE_FETCHED_WIDGETS = 'STORE_FETCHED_WIDGETS'
export const WIDGETS_LOADED = 'WIDGETS_LOADED'

export const STORE_FETCHED_MENUS = 'STORE_FETCHED_MENUS'
export const MENUS_LOADED = 'MENUS_LOADED'

export const STORE_FETCHED_USER = 'STORE_FETCHED_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

export const INCREMENT_LOADING_PROGRESS = 'INCREMENT_LOADING_PROGRESS'
export const RESET_LOADING_PROGRESS = 'RESET_LOADING_PROGRESS'
